### For Data Visualzation

### Loading the libraries
library(VIM)
library(readr)
library(mice)

### Setting the path for current working directory
setwd('/home/anityagupta/documents/dpa/courses/da/project/datasets/cryptocurrencypricehistory')

bit_price <- read.csv('bitcoin_price.csv')
bit_price$Date <- as.Date(bit_price$Date, format = "%B %d,%Y")

aggr_plot_bit_price <- aggr(bit_price, col=c('navyblue','red'), numbers=TRUE, sortVars=TRUE, labels=names(bit_price), cex.axis=.7, gap=3, ylab=c("Histogram of missing data","Pattern"))
#sum(is.na(eth_dataset$`Date(UTC)`))
### boxplot for two attributes
marginplot(bit_price[c(1,6)])

bit_cash_price <- read.csv('bitcoin_price_normalised.csv')
bit_cash_price$Date <- as.Date(bit_cash_price$Date, format = "%B %d,%Y")


aggr_plot_bit_cash_price <- aggr(bit_cash_price, col=c('navyblue','red'), numbers=TRUE, sortVars=TRUE, labels=names(bit_cash_price), cex.axis=.7, gap=3, ylab=c("Histogram of missing data","Pattern"))

### boxplot for two attributes
marginplot(bit_cash_price[c(1,7)])


bit_dataset <- read.csv('bitcoin_dataset_cleaned.csv')
bit_dataset$Date <- as.Date(bit_dataset$Date, format = "%Y-%m-%d %H:%M:%S")


aggr_plot_bit_dataset <- aggr(bit_dataset, col=c('navyblue','red'), numbers=TRUE, sortVars=TRUE, labels=names(bit_dataset), cex.axis=.3, gap=1, ylab=c("Histogram of missing data","Pattern"))

### boxplot for two attributes
marginplot(bit_dataset[c(1,5)])
